---
# handlers file for InstallWebServer
  - name: Restart nginx
    service:
      name: nginx
      state: restarted

  - name: Enable Nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
